/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author ASUS-TUF
 */
public class VentanaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdministrador
     */
    public VentanaAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPestaniaAdmin = new javax.swing.JTabbedPane();
        panelNuevaVenta = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        panelCliente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        subPanelClienteForm = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAreaDireccionCliente = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEmailCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtApeMatCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtApePatCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtIdCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIdClienteBuscar = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        btnResetFormCliente = new javax.swing.JButton();
        btnRegistrarCliente = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();
        btnActualizarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        panelProveedor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        subPanelProveForm = new javax.swing.JPanel();
        txtIdBuscadoProveedor = new javax.swing.JTextField();
        txtNombreProveedor = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblNif = new javax.swing.JLabel();
        txtNif = new javax.swing.JTextField();
        lblContacto = new javax.swing.JLabel();
        txtContactoProveedor = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        lblMunicipio = new javax.swing.JLabel();
        txtMunicipioProveedor = new javax.swing.JTextField();
        txtColoniaProveedor = new javax.swing.JTextField();
        lblColonia = new javax.swing.JLabel();
        txtCalleProveedor = new javax.swing.JTextField();
        lblCalle = new javax.swing.JLabel();
        lblNumExt = new javax.swing.JLabel();
        txtNumExtProveedor = new javax.swing.JTextField();
        lblNumInt = new javax.swing.JLabel();
        txtNumIntProveedor = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefonoProveedor = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtEmailProveedor = new javax.swing.JTextField();
        txtCPProveedor = new javax.swing.JTextField();
        lblCP = new javax.swing.JLabel();
        lblCalleUno = new javax.swing.JLabel();
        txtCalleUnoProveedor = new javax.swing.JTextField();
        lblCalleDos = new javax.swing.JLabel();
        txtCalleDosProveedor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        comboEdoProveedor = new javax.swing.JComboBox<>();
        txtIdProveedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnLimpiarFormProveedor = new javax.swing.JButton();
        subPanelProveBotones = new javax.swing.JPanel();
        btnRegistrarProveedor = new javax.swing.JButton();
        btnBuscarProveedor = new javax.swing.JButton();
        btnActualizarProveedor = new javax.swing.JButton();
        btnEliminarProveedor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProveedor = new javax.swing.JTable();
        panelProducto = new javax.swing.JPanel();
        subPanelProductosForm = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        comboTipoProducto = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtPrecioProducto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        comboMarcaProducto = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txtTallaProducto = new javax.swing.JTextField();
        comboEstatusProducto = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtStockProducto = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaDescripcionProducto = new javax.swing.JTextArea();
        txtIdProducto = new javax.swing.JTextField();
        lblIdProductoBuscar = new javax.swing.JLabel();
        txtIdProductoBuscado = new javax.swing.JTextField();
        comboProveedorProducto = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboCategoriaProducto = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        comboGeneroProducto = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        txtColorProducto = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        comboEstiloProducto = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        comboTemporadaProducto = new javax.swing.JComboBox<>();
        comboColorProducto = new javax.swing.JComboBox<>();
        btnLimpiarFormProducto = new javax.swing.JButton();
        subPanelProductosBotones = new javax.swing.JPanel();
        btnBuscarProducto = new javax.swing.JButton();
        btnActualizarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        btnRegistrarProducto = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPestaniaAdmin.setBackground(new java.awt.Color(255, 255, 255));

        panelNuevaVenta.setBackground(new java.awt.Color(255, 255, 255));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_blancoGrande.png"))); // NOI18N
        jLabel29.setText("jLabel29");

        javax.swing.GroupLayout panelNuevaVentaLayout = new javax.swing.GroupLayout(panelNuevaVenta);
        panelNuevaVenta.setLayout(panelNuevaVentaLayout);
        panelNuevaVentaLayout.setHorizontalGroup(
            panelNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevaVentaLayout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(jLabel28)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        panelNuevaVentaLayout.setVerticalGroup(
            panelNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevaVentaLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevaVentaLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        panelPestaniaAdmin.addTab("Innovasport", panelNuevaVenta);

        panelCliente.setBackground(new java.awt.Color(255, 255, 255));

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Correo", "Telefono", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCliente);
        if (tablaCliente.getColumnModel().getColumnCount() > 0) {
            tablaCliente.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_fondoblanco_chico.PNG"))); // NOI18N

        subPanelClienteForm.setBackground(new java.awt.Color(18, 125, 194));

        txtAreaDireccionCliente.setColumns(20);
        txtAreaDireccionCliente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtAreaDireccionCliente.setRows(5);
        jScrollPane5.setViewportView(txtAreaDireccionCliente);

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Dirección:");

        txtTelefonoCliente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtTelefonoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoClienteKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Teléfono:");

        txtEmailCliente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Correo electrónico:");

        txtApeMatCliente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Apellido materno:");

        txtApePatCliente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellido paterno:");

        txtNombreCliente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        txtIdCliente.setBackground(new java.awt.Color(18, 125, 194));
        txtIdCliente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtIdCliente.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Datos del cliente");

        txtIdClienteBuscar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtIdClienteBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdClienteBuscarKeyTyped(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText(" ID a buscar:");

        btnResetFormCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnResetFormCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnResetFormCliente.setText("Limpiar");
        btnResetFormCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetFormClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subPanelClienteFormLayout = new javax.swing.GroupLayout(subPanelClienteForm);
        subPanelClienteForm.setLayout(subPanelClienteFormLayout);
        subPanelClienteFormLayout.setHorizontalGroup(
            subPanelClienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelClienteFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subPanelClienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelClienteFormLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(subPanelClienteFormLayout.createSequentialGroup()
                        .addGroup(subPanelClienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(subPanelClienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnResetFormCliente)
                                .addGroup(subPanelClienteFormLayout.createSequentialGroup()
                                    .addGroup(subPanelClienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel23))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(subPanelClienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtEmailCliente)
                                        .addComponent(txtTelefonoCliente)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))))
                            .addGroup(subPanelClienteFormLayout.createSequentialGroup()
                                .addGroup(subPanelClienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(subPanelClienteFormLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(13, 13, 13)))
                                .addGap(10, 10, 10)
                                .addGroup(subPanelClienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtApePatCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApeMatCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelClienteFormLayout.createSequentialGroup()
                        .addGroup(subPanelClienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(subPanelClienteFormLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(subPanelClienteFormLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(subPanelClienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(subPanelClienteFormLayout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtIdClienteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(27, 27, 27))))
        );
        subPanelClienteFormLayout.setVerticalGroup(
            subPanelClienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelClienteFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(subPanelClienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtIdClienteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(subPanelClienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(subPanelClienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApePatCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(subPanelClienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApeMatCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(subPanelClienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(subPanelClienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(subPanelClienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnResetFormCliente)
                .addContainerGap())
        );

        btnRegistrarCliente.setBackground(new java.awt.Color(18, 125, 194));
        btnRegistrarCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegistrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarCliente.setText("Registrar");

        btnBuscarCliente.setBackground(new java.awt.Color(18, 125, 194));
        btnBuscarCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBuscarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        btnActualizarCliente.setBackground(new java.awt.Color(18, 125, 194));
        btnActualizarCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnActualizarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarCliente.setText("Actualizar");

        btnEliminarCliente.setBackground(new java.awt.Color(229, 0, 0));
        btnEliminarCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEliminarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCliente.setText("Eliminar");

        javax.swing.GroupLayout panelClienteLayout = new javax.swing.GroupLayout(panelCliente);
        panelCliente.setLayout(panelClienteLayout);
        panelClienteLayout.setHorizontalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subPanelClienteForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelClienteLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(btnRegistrarCliente))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarCliente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelClienteLayout.setVerticalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(subPanelClienteForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(19, 19, 19)
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscarCliente)
                            .addComponent(btnActualizarCliente)
                            .addComponent(btnEliminarCliente)
                            .addComponent(btnRegistrarCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        panelPestaniaAdmin.addTab("Clientes", panelCliente);

        panelProveedor.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_fondoblanco_chico.PNG"))); // NOI18N

        subPanelProveForm.setBackground(new java.awt.Color(18, 125, 194));

        txtIdBuscadoProveedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtIdBuscadoProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdBuscadoProveedorKeyTyped(evt);
            }
        });

        txtNombreProveedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtNombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProveedorActionPerformed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");

        lblNif.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblNif.setForeground(new java.awt.Color(255, 255, 255));
        lblNif.setText("RFC:");

        txtNif.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        lblContacto.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblContacto.setForeground(new java.awt.Color(255, 255, 255));
        lblContacto.setText("Persona de contacto:");

        txtContactoProveedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        lblEstado.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(255, 255, 255));
        lblEstado.setText("Estado:");

        lblMunicipio.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblMunicipio.setForeground(new java.awt.Color(255, 255, 255));
        lblMunicipio.setText("Municipio:");

        txtMunicipioProveedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        txtColoniaProveedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        lblColonia.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblColonia.setForeground(new java.awt.Color(255, 255, 255));
        lblColonia.setText("Colonia:");

        txtCalleProveedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        lblCalle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCalle.setForeground(new java.awt.Color(255, 255, 255));
        lblCalle.setText("Calle:");

        lblNumExt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblNumExt.setForeground(new java.awt.Color(255, 255, 255));
        lblNumExt.setText("N° Ext:");
        lblNumExt.setToolTipText("");

        txtNumExtProveedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtNumExtProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumExtProveedorKeyTyped(evt);
            }
        });

        lblNumInt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblNumInt.setForeground(new java.awt.Color(255, 255, 255));
        lblNumInt.setText("N° Int:");

        txtNumIntProveedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtNumIntProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumIntProveedorKeyTyped(evt);
            }
        });

        lblTelefono.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono.setText("Teléfono:");

        txtTelefonoProveedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtTelefonoProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoProveedorKeyTyped(evt);
            }
        });

        lblCorreo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("Correo electrónico:");

        txtEmailProveedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        txtCPProveedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCPProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCPProveedorKeyTyped(evt);
            }
        });

        lblCP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCP.setForeground(new java.awt.Color(255, 255, 255));
        lblCP.setText("CP:");

        lblCalleUno.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCalleUno.setForeground(new java.awt.Color(255, 255, 255));
        lblCalleUno.setText("Calle 1:");

        txtCalleUnoProveedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        lblCalleDos.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCalleDos.setForeground(new java.awt.Color(255, 255, 255));
        lblCalleDos.setText("Calle 2:");

        txtCalleDosProveedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID a buscar:");

        comboEdoProveedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboEdoProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Chiapas", "Chihuahua", "Ciudad de México", "Coahuila", "Colima", "Durango", "Estado de México", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas" }));

        txtIdProveedor.setEditable(false);
        txtIdProveedor.setBackground(new java.awt.Color(18, 125, 194));
        txtIdProveedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtIdProveedor.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Datos del proveedor");

        btnLimpiarFormProveedor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLimpiarFormProveedor.setText("Limpiar");

        javax.swing.GroupLayout subPanelProveFormLayout = new javax.swing.GroupLayout(subPanelProveForm);
        subPanelProveForm.setLayout(subPanelProveFormLayout);
        subPanelProveFormLayout.setHorizontalGroup(
            subPanelProveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelProveFormLayout.createSequentialGroup()
                .addGroup(subPanelProveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelProveFormLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdBuscadoProveedor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelProveFormLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(subPanelProveFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCorreo)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmailProveedor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelProveFormLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLimpiarFormProveedor))
                    .addGroup(subPanelProveFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(subPanelProveFormLayout.createSequentialGroup()
                        .addGroup(subPanelProveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(subPanelProveFormLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(subPanelProveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEstado)
                                    .addComponent(lblColonia)
                                    .addComponent(lblContacto)
                                    .addComponent(lblNif)
                                    .addComponent(lblNombre)
                                    .addComponent(lblMunicipio)))
                            .addGroup(subPanelProveFormLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblCalle))
                            .addGroup(subPanelProveFormLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblCalleUno))
                            .addGroup(subPanelProveFormLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblCalleDos))
                            .addGroup(subPanelProveFormLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTelefono))
                            .addGroup(subPanelProveFormLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblCP))
                            .addGroup(subPanelProveFormLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblNumExt)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(subPanelProveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMunicipioProveedor)
                            .addComponent(txtColoniaProveedor)
                            .addComponent(txtCalleProveedor)
                            .addComponent(comboEdoProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNif, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtContactoProveedor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelProveFormLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCPProveedor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCalleUnoProveedor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(subPanelProveFormLayout.createSequentialGroup()
                                .addComponent(txtNumExtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(lblNumInt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNumIntProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCalleDosProveedor)
                            .addComponent(txtTelefonoProveedor, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        subPanelProveFormLayout.setVerticalGroup(
            subPanelProveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelProveFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(subPanelProveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdBuscadoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelProveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelProveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelProveFormLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblNif))
                    .addComponent(txtNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelProveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContactoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContacto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelProveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(comboEdoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelProveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMunicipioProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMunicipio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelProveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtColoniaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColonia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelProveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCP)
                    .addComponent(txtCPProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 15, Short.MAX_VALUE)
                .addGroup(subPanelProveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCalle, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCalleProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelProveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumExt)
                    .addComponent(txtNumExtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumInt)
                    .addComponent(txtNumIntProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelProveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCalleUnoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCalleUno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelProveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCalleDosProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCalleDos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelProveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelProveFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(txtEmailProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarFormProveedor)
                .addGap(21, 21, 21))
        );

        subPanelProveBotones.setBackground(new java.awt.Color(255, 255, 255));

        btnRegistrarProveedor.setBackground(new java.awt.Color(18, 125, 194));
        btnRegistrarProveedor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegistrarProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarProveedor.setText("Registrar");

        btnBuscarProveedor.setBackground(new java.awt.Color(18, 125, 194));
        btnBuscarProveedor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBuscarProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarProveedor.setText("Buscar");

        btnActualizarProveedor.setBackground(new java.awt.Color(18, 125, 194));
        btnActualizarProveedor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnActualizarProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarProveedor.setText("Actualizar");

        btnEliminarProveedor.setBackground(new java.awt.Color(229, 0, 0));
        btnEliminarProveedor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEliminarProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarProveedor.setText("Eliminar");

        javax.swing.GroupLayout subPanelProveBotonesLayout = new javax.swing.GroupLayout(subPanelProveBotones);
        subPanelProveBotones.setLayout(subPanelProveBotonesLayout);
        subPanelProveBotonesLayout.setHorizontalGroup(
            subPanelProveBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelProveBotonesLayout.createSequentialGroup()
                .addContainerGap(332, Short.MAX_VALUE)
                .addComponent(btnRegistrarProveedor)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarProveedor)
                .addGap(18, 18, 18)
                .addComponent(btnActualizarProveedor)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarProveedor)
                .addContainerGap())
        );
        subPanelProveBotonesLayout.setVerticalGroup(
            subPanelProveBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelProveBotonesLayout.createSequentialGroup()
                .addGroup(subPanelProveBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarProveedor)
                    .addComponent(btnActualizarProveedor)
                    .addComponent(btnBuscarProveedor)
                    .addComponent(btnRegistrarProveedor))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        tablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "RFC", "Contacto", "CP", "Telefono", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaProveedor);

        javax.swing.GroupLayout panelProveedorLayout = new javax.swing.GroupLayout(panelProveedor);
        panelProveedor.setLayout(panelProveedorLayout);
        panelProveedorLayout.setHorizontalGroup(
            panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subPanelProveForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProveedorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProveedorLayout.createSequentialGroup()
                                .addComponent(subPanelProveBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProveedorLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))
                    .addGroup(panelProveedorLayout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelProveedorLayout.setVerticalGroup(
            panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProveedorLayout.createSequentialGroup()
                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProveedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(subPanelProveForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelProveedorLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(19, 19, 19)
                        .addComponent(subPanelProveBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPestaniaAdmin.addTab("Proveedores", panelProveedor);

        panelProducto.setBackground(new java.awt.Color(255, 255, 255));

        subPanelProductosForm.setBackground(new java.awt.Color(18, 125, 194));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tipo de prenda:");

        comboTipoProducto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboTipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zapato", "Ropa" }));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nombre:");

        txtNombreProducto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Precio:");

        txtPrecioProducto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtPrecioProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioProductoKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Marca;");

        comboMarcaProducto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboMarcaProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adidas", "Reebok", "Jordan", "Nike", "Puma", "Converse", "Champion", "New Balance", "Fila", "Vans", "Crocs" }));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Talla:");

        txtTallaProducto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtTallaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTallaProductoActionPerformed(evt);
            }
        });
        txtTallaProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTallaProductoKeyTyped(evt);
            }
        });

        comboEstatusProducto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboEstatusProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "No disponible" }));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Estatus:");
        jLabel24.setToolTipText("");

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Stock:");

        txtStockProducto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtStockProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockProductoKeyTyped(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Descripción:");

        txtAreaDescripcionProducto.setColumns(20);
        txtAreaDescripcionProducto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtAreaDescripcionProducto.setRows(5);
        jScrollPane3.setViewportView(txtAreaDescripcionProducto);

        txtIdProducto.setEditable(false);
        txtIdProducto.setBackground(new java.awt.Color(18, 125, 194));
        txtIdProducto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtIdProducto.setEnabled(false);

        lblIdProductoBuscar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblIdProductoBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblIdProductoBuscar.setText("ID a buscar:");

        txtIdProductoBuscado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtIdProductoBuscado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdProductoBuscadoKeyTyped(evt);
            }
        });

        comboProveedorProducto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboProveedorProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboProveedorProductoItemStateChanged(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Proveedor: ");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Categoría:");

        comboCategoriaProducto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Género:");

        comboGeneroProducto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboGeneroProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caballero", "Dama", "Jjunior", "Niña", "Niño", "Unixex" }));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Color:");

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Estilo:");

        comboEstiloProducto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboEstiloProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aire", "Retro", "Confort", "Formales", "Aire libre" }));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Temporada:");

        comboTemporadaProducto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboTemporadaProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Otoño-Invierno", "Primavera-Verano" }));

        comboColorProducto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboColorProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NEGRO", "AZUL", "BLANCO", "ROJO", "ROSA", "AMARILLO", "GRIS", "MORADO" }));

        btnLimpiarFormProducto.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpiarFormProducto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLimpiarFormProducto.setText("Limpiar");
        btnLimpiarFormProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFormProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subPanelProductosFormLayout = new javax.swing.GroupLayout(subPanelProductosForm);
        subPanelProductosForm.setLayout(subPanelProductosFormLayout);
        subPanelProductosFormLayout.setHorizontalGroup(
            subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelProductosFormLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(subPanelProductosFormLayout.createSequentialGroup()
                        .addGroup(subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdProductoBuscar)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboTemporadaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboGeneroProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTallaProducto)
                            .addComponent(comboMarcaProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrecioProducto)
                            .addComponent(comboTipoProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboCategoriaProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboProveedorProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdProductoBuscado)
                            .addComponent(txtNombreProducto)
                            .addComponent(comboEstiloProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(subPanelProductosFormLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(23, 23, 23)
                        .addComponent(txtColorProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboColorProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelProductosFormLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnLimpiarFormProducto))
                    .addGroup(subPanelProductosFormLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(subPanelProductosFormLayout.createSequentialGroup()
                                .addGroup(subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))
                                .addGap(33, 33, 33)
                                .addGroup(subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtStockProducto)
                                    .addComponent(comboEstatusProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel26)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        subPanelProductosFormLayout.setVerticalGroup(
            subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelProductosFormLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdProductoBuscar)
                    .addComponent(txtIdProductoBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEstatusProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboProveedorProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel25)
                    .addComponent(txtStockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCategoriaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelProductosFormLayout.createSequentialGroup()
                        .addGroup(subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(comboMarcaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtTallaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(comboGeneroProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtColorProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboColorProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(comboEstiloProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(subPanelProductosFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(comboTemporadaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnLimpiarFormProducto)
                .addContainerGap())
        );

        btnBuscarProducto.setBackground(new java.awt.Color(18, 125, 194));
        btnBuscarProducto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBuscarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarProducto.setText("Buscar");

        btnActualizarProducto.setBackground(new java.awt.Color(18, 125, 194));
        btnActualizarProducto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnActualizarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarProducto.setText("Actualizar");

        btnEliminarProducto.setBackground(new java.awt.Color(229, 0, 0));
        btnEliminarProducto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEliminarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarProducto.setText("Eliminar");

        btnRegistrarProducto.setBackground(new java.awt.Color(18, 125, 194));
        btnRegistrarProducto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegistrarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarProducto.setText("Registrar");

        javax.swing.GroupLayout subPanelProductosBotonesLayout = new javax.swing.GroupLayout(subPanelProductosBotones);
        subPanelProductosBotones.setLayout(subPanelProductosBotonesLayout);
        subPanelProductosBotonesLayout.setHorizontalGroup(
            subPanelProductosBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelProductosBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarProducto)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarProducto)
                .addGap(18, 18, 18)
                .addComponent(btnActualizarProducto)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarProducto))
        );
        subPanelProductosBotonesLayout.setVerticalGroup(
            subPanelProductosBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelProductosBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnActualizarProducto)
                .addComponent(btnBuscarProducto)
                .addComponent(btnEliminarProducto)
                .addComponent(btnRegistrarProducto))
        );

        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Proveedor", "Categoria", "Precio", "Marca", "Color", "Estatus", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablaProducto);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_fondoblanco_chico.PNG"))); // NOI18N

        javax.swing.GroupLayout panelProductoLayout = new javax.swing.GroupLayout(panelProducto);
        panelProducto.setLayout(panelProductoLayout);
        panelProductoLayout.setHorizontalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoLayout.createSequentialGroup()
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(subPanelProductosForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProductoLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelProductoLayout.createSequentialGroup()
                                .addGap(281, 281, 281)
                                .addComponent(jLabel4))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductoLayout.createSequentialGroup()
                        .addGap(505, 505, 505)
                        .addComponent(subPanelProductosBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        panelProductoLayout.setVerticalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoLayout.createSequentialGroup()
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(11, 11, 11)
                        .addComponent(subPanelProductosBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4))
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(subPanelProductosForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        panelPestaniaAdmin.addTab("Productos", panelProducto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(panelPestaniaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 1323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelPestaniaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProveedorActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void comboProveedorProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboProveedorProductoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboProveedorProductoItemStateChanged

    private void txtPrecioProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioProductoKeyTyped
        //Validacion de solo decimales en caja de texto
        char caracter = evt.getKeyChar();
        
        if( ((caracter < '0') || (caracter > '9' ))  && (caracter != KeyEvent.VK_BACK_SPACE) && ( caracter != '.' || txtPrecioProducto.getText().contains(".") )){
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioProductoKeyTyped

    private void tablaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductoMouseClicked
        //==========================================================
        //Función donde se deecta un clic en la tabla
        //=========================================================
    }//GEN-LAST:event_tablaProductoMouseClicked

    private void btnResetFormClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetFormClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetFormClienteActionPerformed

    private void btnLimpiarFormProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFormProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarFormProductoActionPerformed

    private void txtIdBuscadoProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdBuscadoProveedorKeyTyped
        // VALIDAR SOLO NUMEROS COMO ENTRADA
        char digito = evt.getKeyChar(); //Se obtiene el caracter digitado
        
        //Se valida que el caracter este dentro del rango de productos posibles a comprar
        if( ((digito < '0' || digito > '9')) && (digito != '\b') ){
            evt.consume(); // ignorar el evento de teclado
            System.out.println("CARACTER NO VALIDO");
            
        }else{
            
        }
    }//GEN-LAST:event_txtIdBuscadoProveedorKeyTyped

    private void txtIdClienteBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdClienteBuscarKeyTyped
        // VALIDAR SOLO NUMEROS COMO ENTRADA
        char digito = evt.getKeyChar(); //Se obtiene el caracter digitado
        
        //Se valida que el caracter este dentro del rango de productos posibles a comprar
        if( ((digito < '0' || digito > '9')) && (digito != '\b') ){
            evt.consume(); // ignorar el evento de teclado
            System.out.println("CARACTER NO VALIDO");
            
        }else{
            
        }
    }//GEN-LAST:event_txtIdClienteBuscarKeyTyped

    private void txtIdProductoBuscadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdProductoBuscadoKeyTyped
        // VALIDAR SOLO NUMEROS COMO ENTRADA
        char digito = evt.getKeyChar(); //Se obtiene el caracter digitado
        
        //Se valida que el caracter este dentro del rango de productos posibles a comprar
        if( ((digito < '0' || digito > '9')) && (digito != '\b') ){
            evt.consume(); // ignorar el evento de teclado
            System.out.println("CARACTER NO VALIDO");
            
        }else{
            
        }
    }//GEN-LAST:event_txtIdProductoBuscadoKeyTyped

    private void txtStockProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockProductoKeyTyped
        // VALIDAR SOLO NUMEROS COMO ENTRADA
        char digito = evt.getKeyChar(); //Se obtiene el caracter digitado
        
        //Se valida que el caracter este dentro del rango de productos posibles a comprar
        if( ((digito < '0' || digito > '9')) && (digito != '\b') ){
            evt.consume(); // ignorar el evento de teclado
            System.out.println("CARACTER NO VALIDO");
            
        }else{
            
        }
    }//GEN-LAST:event_txtStockProductoKeyTyped

    private void txtTallaProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTallaProductoKeyTyped
        
    }//GEN-LAST:event_txtTallaProductoKeyTyped

    private void txtTelefonoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoClienteKeyTyped
        // VALIDAR SOLO NUMEROS COMO ENTRADA
        char digito = evt.getKeyChar(); //Se obtiene el caracter digitado
        
        //Se valida que el caracter este dentro del rango de productos posibles a comprar
        if( ((digito < '0' || digito > '9')) && (digito != '\b') ){
            evt.consume(); // ignorar el evento de teclado
            System.out.println("CARACTER NO VALIDO");
            
        }else{
            
        }
    }//GEN-LAST:event_txtTelefonoClienteKeyTyped

    private void txtNumExtProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumExtProveedorKeyTyped
        // VALIDAR SOLO NUMEROS COMO ENTRADA
        char digito = evt.getKeyChar(); //Se obtiene el caracter digitado
        
        //Se valida que el caracter este dentro del rango de productos posibles a comprar
        if( ((digito < '0' || digito > '9')) && (digito != '\b') ){
            evt.consume(); // ignorar el evento de teclado
            System.out.println("CARACTER NO VALIDO");
            
        }else{
            
        }
    }//GEN-LAST:event_txtNumExtProveedorKeyTyped

    private void txtNumIntProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumIntProveedorKeyTyped
        // VALIDAR SOLO NUMEROS COMO ENTRADA
        char digito = evt.getKeyChar(); //Se obtiene el caracter digitado
        
        //Se valida que el caracter este dentro del rango de productos posibles a comprar
        if( ((digito < '0' || digito > '9')) && (digito != '\b') ){
            evt.consume(); // ignorar el evento de teclado
            System.out.println("CARACTER NO VALIDO");
            
        }else{
            
        }
    }//GEN-LAST:event_txtNumIntProveedorKeyTyped

    private void txtCPProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPProveedorKeyTyped
        // VALIDAR SOLO NUMEROS COMO ENTRADA
        char digito = evt.getKeyChar(); //Se obtiene el caracter digitado
        
        //Se valida que el caracter este dentro del rango de productos posibles a comprar
        if( ((digito < '0' || digito > '9')) && (digito != '\b') ){
            evt.consume(); // ignorar el evento de teclado
            System.out.println("CARACTER NO VALIDO");
            
        }else{
            
        }
    }//GEN-LAST:event_txtCPProveedorKeyTyped

    private void txtTelefonoProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoProveedorKeyTyped
        // VALIDAR SOLO NUMEROS COMO ENTRADA
        char digito = evt.getKeyChar(); //Se obtiene el caracter digitado
        
        //Se valida que el caracter este dentro del rango de productos posibles a comprar
        if( ((digito < '0' || digito > '9')) && (digito != '\b') ){
            evt.consume(); // ignorar el evento de teclado
            System.out.println("CARACTER NO VALIDO");
            
        }else{
            
        }
    }//GEN-LAST:event_txtTelefonoProveedorKeyTyped

    private void txtTallaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTallaProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTallaProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarCliente;
    public javax.swing.JButton btnActualizarProducto;
    public javax.swing.JButton btnActualizarProveedor;
    public javax.swing.JButton btnBuscarCliente;
    public javax.swing.JButton btnBuscarProducto;
    public javax.swing.JButton btnBuscarProveedor;
    public javax.swing.JButton btnEliminarCliente;
    public javax.swing.JButton btnEliminarProducto;
    public javax.swing.JButton btnEliminarProveedor;
    public javax.swing.JButton btnLimpiarFormProducto;
    public javax.swing.JButton btnLimpiarFormProveedor;
    public javax.swing.JButton btnRegistrarCliente;
    public javax.swing.JButton btnRegistrarProducto;
    public javax.swing.JButton btnRegistrarProveedor;
    public javax.swing.JButton btnResetFormCliente;
    public javax.swing.JComboBox<String> comboCategoriaProducto;
    public javax.swing.JComboBox<String> comboColorProducto;
    public javax.swing.JComboBox<String> comboEdoProveedor;
    public javax.swing.JComboBox<String> comboEstatusProducto;
    public javax.swing.JComboBox<String> comboEstiloProducto;
    public javax.swing.JComboBox<String> comboGeneroProducto;
    public javax.swing.JComboBox<String> comboMarcaProducto;
    public javax.swing.JComboBox<String> comboProveedorProducto;
    public javax.swing.JComboBox<String> comboTemporadaProducto;
    public javax.swing.JComboBox<String> comboTipoProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JLabel lblCP;
    public javax.swing.JLabel lblCalle;
    public javax.swing.JLabel lblCalleDos;
    public javax.swing.JLabel lblCalleUno;
    public javax.swing.JLabel lblColonia;
    public javax.swing.JLabel lblContacto;
    public javax.swing.JLabel lblCorreo;
    public javax.swing.JLabel lblEstado;
    public javax.swing.JLabel lblIdProductoBuscar;
    public javax.swing.JLabel lblMunicipio;
    public javax.swing.JLabel lblNif;
    public javax.swing.JLabel lblNombre;
    public javax.swing.JLabel lblNumExt;
    public javax.swing.JLabel lblNumInt;
    public javax.swing.JLabel lblTelefono;
    public javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelNuevaVenta;
    public javax.swing.JTabbedPane panelPestaniaAdmin;
    public javax.swing.JPanel panelProducto;
    public javax.swing.JPanel panelProveedor;
    private javax.swing.JPanel subPanelClienteForm;
    private javax.swing.JPanel subPanelProductosBotones;
    private javax.swing.JPanel subPanelProductosForm;
    private javax.swing.JPanel subPanelProveBotones;
    private javax.swing.JPanel subPanelProveForm;
    public javax.swing.JTable tablaCliente;
    public javax.swing.JTable tablaProducto;
    public javax.swing.JTable tablaProveedor;
    public javax.swing.JTextField txtApeMatCliente;
    public javax.swing.JTextField txtApePatCliente;
    public javax.swing.JTextArea txtAreaDescripcionProducto;
    public javax.swing.JTextArea txtAreaDireccionCliente;
    public javax.swing.JTextField txtCPProveedor;
    public javax.swing.JTextField txtCalleDosProveedor;
    public javax.swing.JTextField txtCalleProveedor;
    public javax.swing.JTextField txtCalleUnoProveedor;
    public javax.swing.JTextField txtColoniaProveedor;
    public javax.swing.JTextField txtColorProducto;
    public javax.swing.JTextField txtContactoProveedor;
    public javax.swing.JTextField txtEmailCliente;
    public javax.swing.JTextField txtEmailProveedor;
    public javax.swing.JTextField txtIdBuscadoProveedor;
    public javax.swing.JTextField txtIdCliente;
    public javax.swing.JTextField txtIdClienteBuscar;
    public javax.swing.JTextField txtIdProducto;
    public javax.swing.JTextField txtIdProductoBuscado;
    public javax.swing.JTextField txtIdProveedor;
    public javax.swing.JTextField txtMunicipioProveedor;
    public javax.swing.JTextField txtNif;
    public javax.swing.JTextField txtNombreCliente;
    public javax.swing.JTextField txtNombreProducto;
    public javax.swing.JTextField txtNombreProveedor;
    public javax.swing.JTextField txtNumExtProveedor;
    public javax.swing.JTextField txtNumIntProveedor;
    public javax.swing.JTextField txtPrecioProducto;
    public javax.swing.JTextField txtStockProducto;
    public javax.swing.JTextField txtTallaProducto;
    public javax.swing.JTextField txtTelefonoCliente;
    public javax.swing.JTextField txtTelefonoProveedor;
    // End of variables declaration//GEN-END:variables
}
